### ISSUE TITLE
AES compatibility: some shared buffers rejected that Go would accept

### ISSUE THREAD

**Issue by dagood** [golang-fips/openssl#106]
This is a theoretical issue--I haven't seen it hit anywhere. I spotted it when reviewing something in the CNG backend and see it's present here too. Example:

```go
// aes_test.go
func TestEncryptSharedBufferWithoutLengthAdjustment(t *testing.T) {
	key := []byte("D249BF6DEC97B1EBD69BC4D6B3A3C49D")
	c, _ := NewAESCipher(key)
	// c, _ = aes.NewCipher(key) // This doesn't panic.
	srcPlusDst := make([]byte, c.BlockSize()*2)
	src := srcPlusDst
	dst := srcPlusDst[c.BlockSize():]
	c.Encrypt(dst, src) // panic: crypto/cipher: invalid buffer overlap
}
```

It's because this line:

https://github.com/golang-fips/openssl/blob/b95716c57aef15cb4943f9850cfe34480c547ae4/aes.go#L141

is stricter than upstream's `if alias.InexactOverlap(dst[:BlockSize], src[:BlockSize]) {`
https://github.com/golang/go/blob/795e779610cd1ef8ad4c137c067a23ace1190115/src/crypto/aes/cipher.go#L65

It looks like `aesCBC.CryptBlocks` has a similar difference, and maybe more places.

I figured I'd file this first to make sure this is actually an issue.

**Comment by qmuntal** [comment]
Agree that this could cause compatibility issues and should be fixed.

Some background: this has been cargo-culted from the boring bindings, which has the same issue:

https://github.com/golang/go/blob/5622128a77b4af5e5dc02edf53ecac545e3af730/src/crypto/internal/boring/aes.go#L98

The boring package implemented the aliasing checks before `crypto/aes`. I suspect that when doing the later they found this issue and fixed it, but without porting it to `crypto/internal/boring`.

**Comment by dagood** [comment]
Thanks, I'll submit a PR here, then also open an issue+CL upstream in case they want to take it for Boring.
