### ISSUE TITLE
Implement encoding.BinaryAppender for all openssl-backed crypto hashes

### ISSUE THREAD

**Issue by dagood** [golang-fips/openssl#148]
I believe we need to implement encoding.BinaryAppender here so that our hash works with this change coming in 1.24:

* 601776: crypto: implement encoding.BinaryAppender for all crypto hashes | https://go-review.googlesource.com/c/go/+/601776
* https://github.com/golang/go/issues/62384

(Haven't investigated much, but spotted the CL with a search/alert @qmuntal set up and wanted to file this.)

**Comment by qmuntal** [comment]
Done in #170.
