### ISSUE TITLE
Rename this repo from openssl-fips to openssl

### ISSUE THREAD

**Issue by qmuntal** [golang-fips/openssl#16]
The name of this org (`golang-fips`) already contains the `fips` sufix, so having it also in the repo name seems redundant and is even cumbersome to say it loud.

I propose to rename this repo (and the Go module) from `github.com/golang-fips/openssl-fips` to `github.com/golang-fips/openssl`.

This change will probably cause some headaches to `github.com/golang-fips/go`, as the name of the module is hardcoded there and it will have to be updated.

@derekparker

**Comment by derekparker** [comment]
I agree I think a name change is in order, the current naming scheme is redundant. I think however just calling the repo `openssl` is somewhat confusing, so how about something like `github.com/golang-fips/openssl-bindings` or something similar, I'm definitely open to ideas.

@dbenoit17

**Comment by dbenoit17** [comment]
Maybe something like `openssl-go`?  It's concise and makes clear these are go bindings vs eg. a mirror of openssl.  I think it's less redundant than `openssl-fips`, and upstream has set the precedent for this level of redundancy anyway with `golang/go`.

**Comment by qmuntal** [comment]
> Maybe something like openssl-go? It's concise and makes clear these are go bindings vs eg. a mirror of openssl. I think it's less redundant than openssl-fips, and upstream has set the precedent for this level of redundancy anyway with golang/go

I like the idea, but I normally prefer to add `go` as a prefix instead of as a suffix, so I would vote for `go-openssl`.

**Comment by qmuntal** [comment]
How do we move this forward? I don't care if we rename this repo or archive it + create a new one with the proper name, as our toolchain is still not using it. @derekparker your call.

**Comment by qmuntal** [comment]
Friendly bump.

**Comment by derekparker** [comment]
Done.
